- name: Deploy stellar controller
  include_role:
    name: k8s/utils/kubectl-create-or-replace
  vars:
    controller_kind: deploy
    controller_name: "{{db_app_name}}"
    controller_template: "{% if db_type == 'postgresql' %}db.yaml.j2{% else %}mysql.yaml.j2{% endif %}"
